contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #mtbc-resistotyper-nf channel"
    url: https://nfcore.slack.com/channels/mtbc-resistotyper-nf
    about: Discussion about the mycobactopia-org/mtbc-resistotyper-nf pipeline
